version: '3.1'
services:
   
  postgres:
    container_name: postgres
    image:   postgres
    restart: "always"
    ports:
      - 5432:5432 
    volumes:
      - ./postgredb:/var/lib/postgresql/data
    env_file: .env

  redis:
    container_name:  redis
    image:  redis
    ports:
      - 6379:6379