BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBBBBBBBBBBBBBB          
BBBBB BBBBB
  XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX
BBBBBBBB


XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXX 
    BBBBB BBBBBBB
      XXXXXXXXX XXXXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXXXXX XXXXXXXX XXXXXXXXX
              BBBBBBB BBBBBBBBBBBBBBB
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXXXXXX
    BBBBBBBB
  XXXXXX