
BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBB
  XXXXXXXXXXXX XXXXXXXXXXXXXXXX
BBBBBBBB

BBBBB BBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBXX
BBBBBBBB

XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXX 
    BBBBB BBBBBBB
      XXXXXXXXX XXXXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXXXXX XXXXXXXXXXXXX
            XXXXXX
            XXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXXXXXXXXX XXXX XXXXXXXXX XXXXX XXXX XXXXX XXXXXXX XXXXXX XXX XXXXX XXXXX XXXXXXXXXXXX XXX XXXXXXX X XXX XXXXXXXX
              XXXX XXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXX
                  BBBBBBBBBB
                  BB BBBBBBBBBBB
                    XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            BBB BBBB BBBBB BB BBBBBBBBBBBBBBBBB
                                XXXXXXXXXXXXXXXXX
                            BBBBBB
                        XXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXX
                    XXXXXX
                  BBBBB
                  XXX XXXXXXXXXXXXXXXX XXXXX
                    XXX XXXXXXXXXXXXXXXXX
                      
                      
                    XXXXX      
                  XXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
                  XXXXXX
                  XXXX
                  XXXXXXX XX XXXXXXXX XX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX
              XXXXXX 
            XXXXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXXXXXX
    BBBBBBBB
  XXXXXX