BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBB
  XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
BBBBBBBB

BBBBB BBB
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBXX
BBBBBBBB

XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXX 
    BBBBB BBBBBBB
      XXXX XXXX XXXXXXXXX XXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXX
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXXX XXXXXX XXXXXXXX XXXX XXXXX XXXXXXXXXXXXXX XXXXXX
            XXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXX XXXXXXX X X XXXX XXXXXXX XXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXX
              BBBBBBB BBBBBBBBBBBBBBB
              BB BBBBBBBBBBB
                XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                        BBB BBBB BBBBB BB BBBBBBBBBBBBBBBBB
                            XXXXXXXXXXXXXXXXX
                        BBBBBB
                    XXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX
                XXXXXX
              BBBBB
              XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                BBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXX
                  
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXX
                  
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX  X
                    XXXX
                  XXXXXXXXX
                XXXXXX
              XXXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXXXXXX
      XXXX XXXX XXXXXXXXX XXX XXX 
    BBBBBBBB
  XXXXXX

BBBBB BB
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBXXXXXXXXXXX 
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX 
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXX
BBBBBBBB