BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBB
  XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
BBBBBBBB

XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXX 
    BBBBB BBBBBBB
      XXXXXXXXX XXXXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
              BBBBBBB BBBBBBBBBBBBBBB
            XXXXXX
            XX XXXXXXBBB BBBBBBBX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXX XXXXXX
          XXXXXX
        XXXXXX
      XXXXXXXXXX
    BBBBBBBB
  XXXXXX