# Generated by Django 4.0.10 on 2023-10-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(help_text='Max 100 character', verbose_name='Description of the person')),
                ('description_en', models.TextField(help_text='Max 100 character', null=True, verbose_name='Description of the person')),
                ('description_az', models.TextField(help_text='Max 100 character', null=True, verbose_name='Description of the person')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the person')),
                ('image', models.ImageField(upload_to='core_image', verbose_name='Image of the person')),
            ],
            options={
                'verbose_name': 'Core',
                'verbose_name_plural': 'All Core',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
            },
        ),
    ]
