# Generated by Django 4.0.10 on 2024-08-25 11:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Max 100 characters', max_length=100, verbose_name='Title of the author')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'All Author',
            },
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Max 100 character', max_length=100, verbose_name='Title of the blog')),
                ('title_en', models.CharField(help_text='Max 100 character', max_length=100, null=True, verbose_name='Title of the blog')),
                ('title_az', models.CharField(help_text='Max 100 character', max_length=100, null=True, verbose_name='Title of the blog')),
                ('description', models.TextField(help_text='Max 1000 characters', verbose_name='Description of the blog')),
                ('description_en', models.TextField(help_text='Max 1000 characters', null=True, verbose_name='Description of the blog')),
                ('description_az', models.TextField(help_text='Max 1000 characters', null=True, verbose_name='Description of the blog')),
                ('is_advice', models.BooleanField(default=True, verbose_name='Is this advice blog?')),
                ('file', models.FileField(null=True, upload_to='file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'jpg', 'avi', 'mp3', 'mp4', 'webp', 'mkv', 'gi', 'jpeg', 'png', 'ogg', 'html', 'htm', 'wmv'])])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author', verbose_name='Author  of the blog')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'All Blog',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('Image', 'Image'), ('Video', 'Video'), ('Audio', 'Audio')], help_text='Max 100 character', max_length=100, verbose_name='Name of the category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'All Category',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name:')),
                ('email', models.EmailField(max_length=254, verbose_name='Email adsress:')),
                ('comment', models.TextField(verbose_name='Comment:')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogs')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'All Comment',
            },
        ),
        migrations.AddField(
            model_name='blogs',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Category of the blog'),
        ),
    ]
