# Generated by Django 4.0.10 on 2023-10-13 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='description',
        ),
        migrations.RemoveField(
            model_name='author',
            name='description_az',
        ),
        migrations.RemoveField(
            model_name='author',
            name='description_en',
        ),
    ]
