# Generated by Django 4.0.10 on 2023-10-13 14:32

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name of the category')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Name of the category')),
                ('name_az', models.CharField(max_length=100, null=True, verbose_name='Name of the category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'All Category',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Code of the color')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the color')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Name of the color')),
                ('name_az', models.CharField(max_length=100, null=True, verbose_name='Name of the color')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'All Color',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='product_image')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name of the manufacturer')),
            ],
            options={
                'verbose_name': 'Product Manufacturer',
                'verbose_name_plural': 'Product Manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='old_price')),
                ('price', models.PositiveIntegerField()),
                ('sale', models.BooleanField(default=True)),
                ('title', models.CharField(help_text='Max 1000 character', max_length=100, verbose_name='Title of the product')),
                ('description', models.TextField(verbose_name='Description of the product')),
                ('description_en', models.TextField(null=True, verbose_name='Description of the product')),
                ('description_az', models.TextField(null=True, verbose_name='Description of the product')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Category of the Product')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.manufacturer', verbose_name='Manufacturer of the Product')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'All Products',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quality_rating', models.PositiveIntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')])),
                ('price_rating', models.PositiveIntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')])),
                ('value_rating', models.PositiveIntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')])),
                ('nickname', models.CharField(max_length=100, verbose_name='Nickname')),
                ('comment', models.TextField(verbose_name='Review')),
                ('comment_en', models.TextField(null=True, verbose_name='Review')),
                ('comment_az', models.TextField(null=True, verbose_name='Review')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
            },
        ),
        migrations.CreateModel(
            name='Product_version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ImageField(upload_to='product_image')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_version_color', to='product.color', verbose_name='Color of the product')),
                ('image', models.ManyToManyField(related_name='product_version_image', to='product.image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_version', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Version',
                'verbose_name_plural': 'Product Versions',
            },
        ),
    ]
